name: Build Android APK
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Buildozer
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip zip unzip openjdk-17-jdk git
          python3 -m pip install --user buildozer

      - name: Generate project from bootstrap
        run: |
          python3 bootstrap.py
          ls -la

      - name: Build APK (debug)
        run: |
          export PATH=$HOME/.local/bin:$PATH
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: veresia-apk
          path: bin/*.apk
